cabal-version:      3.0
name:               nix-iac
version:            0.1.0.0
synopsis:           Constrained, idempotent IaC orchestration primitives
license:            BSD-3-Clause
build-type:         Simple

common opts
  default-language: GHC2021
  ghc-options:      -Wall -Wcompat -Wunused-packages -Werror=missing-fields
  build-depends:
      base                 ^>= 4.20
    , text
    , bytestring
    , process
    , aeson
    , directory
    , filepath
    , containers
    , temporary
    , unix

library
  import:           opts
  hs-source-dirs:   src
  exposed-modules:
      NixIac
    , NixIac.Apply
    , NixIac.Config
    , NixIac.Deploy
    , NixIac.Nixify
    , NixIac.Probe
    , NixIac.Reboot
    , NixIac.Run
    , NixIac.Sops
    , NixIac.TfState

executable infra
  import:           opts
  hs-source-dirs:   app
  main-is:          Main.hs
  build-depends:    nix-iac
