cabal-version:      3.0
name:               nix-iac
version:            0.2.0.0
synopsis:           Typed-handle DSL backend for Nix-native infra orchestration
license:            BSD-3-Clause
build-type:         Simple

common opts
  default-language: GHC2021
  ghc-options:      -Wall -Wcompat -Wunused-packages -Werror=missing-fields
  build-depends:
      base                 ^>= 4.20
    , aeson
    , bytestring
    , text
    , process
    , directory
    , filepath
    , containers
    , temporary
    , unix

library
  import:           opts
  hs-source-dirs:   src
  exposed-modules:
      NixIac.Orchestrator
    , NixIac.Plan
    , NixIac.Deploy
    , NixIac.Exec
    , NixIac.Nixify
    , NixIac.Probe
    , NixIac.Reboot
    , NixIac.Run
    , NixIac.Sops
    , NixIac.SshOpts
