# Constrained tofu+nixos-anywhere+colmena orchestration with sops integration.
#
# Consumers should ONLY edit:
#   - their terranix modules (the infrastructure description)
#   - their nixosConfigurations / colmenaHive (the system declarations)
#   - the `mkApps` call (which sops file, which tfvars, per-host secret routing)
#
# Everything else is FIXED.
#
# Design:
#   1. A single sops file (encrypted to one operator key) is the source of truth
#      for cloud creds, ssh access, and any host-bound secrets that originate
#      from a human (signing keys, API tokens).
#   2. Per-host SSH and age keypairs are generated by the deploy script and
#      stored in tfstate as `terraform_data` resources with `ignore_changes` —
#      regenerated only on destroy/recreate.
#   3. Server-side secrets are NEVER stored on disk in the repo encrypted to
#      the server. At deploy time, the script decrypts the operator sops file,
#      pulls fresh secrets from tfstate (CI access keys, etc), bundles them
#      into an ephemeral sops file encrypted ONLY to the host's age pubkey
#      (read from tfstate output), and ships it to the host. No `.sops.yaml`
#      anywhere, no committed buildfarm recipient.

{ pkgs, system, terranix, colmena }:

let
  inherit (pkgs) lib;
  nixos-anywhere = "github:nix-community/nixos-anywhere";

  # Common preamble: render terranix → JSON, init backend, decrypt operator sops.
  preamble = { stateDir, tfConfig, sopsFile }: ''
    root="$(git rev-parse --show-toplevel)"
    tf_dir="$root/${stateDir}"
    tmp="$(mktemp -d)"
    chmod 700 "$tmp"
    trap 'rm -rf "$tmp"' EXIT

    mkdir -p "$tf_dir"
    install -m 644 ${tfConfig} "$tf_dir/config.tf.json"
    ( cd "$tf_dir" && tofu init -input=false -reconfigure >/dev/null )

    # Decrypt operator sops file (asks GPG agent on first run per session)
    sops --config /dev/null -d "${toString sopsFile}" > "$tmp/plain.yaml"
    chmod 600 "$tmp/plain.yaml"
  '';

  # Export env vars from sops keys (raw — caller picks the env var name).
  envFromSopsScript = envFromSops:
    lib.concatStringsSep "\n" (lib.mapAttrsToList (varName: sopsKey: ''
      export ${varName}="$(yq -r '.${sopsKey}' "$tmp/plain.yaml")"
    '') envFromSops);

  mkHostApp = {
    name, ipOutput, sshPrivOutput, sshPubOutput, agePrivOutput, agePubOutput,
    serverSecrets, serverSecretsFromTfState, serverSecretsPath,
    stateDir, tfConfig, sopsFile, envFromSops,
  }: pkgs.writeShellApplication {
      excludeShellChecks = [ "SC2155" "SC2046" "SC2086" ];
    name = "infra-${name}";
    runtimeInputs = [
      pkgs.opentofu pkgs.git pkgs.openssh pkgs.coreutils
      pkgs.sops pkgs.age pkgs.yq-go pkgs.jq
      colmena.packages.${system}.colmena
    ];
    text = ''
      ${preamble { inherit stateDir tfConfig sopsFile; }}
      ${envFromSopsScript envFromSops}

      # If host's keypairs are not yet in tfstate, generate fresh and pass via TF_VAR.
      # `terraform_data` with `ignore_changes` pins them after first apply.
      if ! ( cd "$tf_dir" && tofu output -raw ${agePrivOutput} >/dev/null 2>&1 ); then
        echo "==> ${name}: first apply, generating SSH + age keypairs"
        age-keygen -o "$tmp/age.key" 2>/dev/null
        export TF_VAR_${name}_age_priv="$(cat "$tmp/age.key")"
        export TF_VAR_${name}_age_pub="$(age-keygen -y "$tmp/age.key")"
        ssh-keygen -t ed25519 -N "" -C "${name}" -f "$tmp/ssh.key" >/dev/null
        export TF_VAR_${name}_ssh_priv="$(cat "$tmp/ssh.key")"
        export TF_VAR_${name}_ssh_pub="$(cat "$tmp/ssh.key.pub")"
      else
        # Pass placeholders; terraform_data ignore_changes makes these no-ops
        export TF_VAR_${name}_age_priv=ignored
        export TF_VAR_${name}_age_pub=ignored
        export TF_VAR_${name}_ssh_priv=ignored
        export TF_VAR_${name}_ssh_pub=ignored
      fi

      ( cd "$tf_dir" && tofu apply -auto-approve -input=false )

      ip="$(cd "$tf_dir" && tofu output -raw ${ipOutput})"
      age_pub="$(cd "$tf_dir" && tofu output -raw ${agePubOutput})"
      age_priv="$(cd "$tf_dir" && tofu output -raw ${agePrivOutput})"
      ssh_priv="$(cd "$tf_dir" && tofu output -raw ${sshPrivOutput})"
      echo "==> ${name}: $ip"

      # Materialize SSH key for this deploy
      umask 077
      printf '%s\n' "$ssh_priv" > "$tmp/ssh.key"
      chmod 600 "$tmp/ssh.key"

      # Build server-bound secrets blob: signing keys, tokens (from sops) +
      # tfstate-sourced creds (CI keys etc). Encrypted ONLY to the host age pub.
      jq -n \
        ${lib.concatMapStringsSep " \\\n        " (k:
          ''--arg ${k} "$(yq -r '.${k}' "$tmp/plain.yaml")" ''
        ) serverSecrets} \
        ${lib.concatMapStringsSep " \\\n        " (entry:
          let varName = entry.name; tfOutput = entry.value; in
          ''--arg ${varName} "$(cd "$tf_dir" && tofu output -raw ${tfOutput})" ''
        ) (lib.attrsToList serverSecretsFromTfState)} \
        '{${
          lib.concatStringsSep ", " (
            (map (k: "${k}: $${k}") serverSecrets) ++
            (map (e: "${e.name}: $${e.name}") (lib.attrsToList serverSecretsFromTfState))
          )
        }}' > "$tmp/server-plain.json"
      yq -P "$tmp/server-plain.json" > "$tmp/server-plain.yaml"
      sops --config /dev/null --encrypt --input-type yaml --output-type yaml --age "$age_pub" "$tmp/server-plain.yaml" \
        > "$tmp/server-secrets.yaml"

      # Probe and branch
      if ssh -i "$tmp/ssh.key" \
             -o StrictHostKeyChecking=accept-new \
             -o UserKnownHostsFile="$tf_dir/known_hosts" \
             -o ConnectTimeout=10 \
             -o BatchMode=yes \
             "root@$ip" "test -e /etc/NIXOS" 2>/dev/null; then
        echo "==> NixOS detected — colmena update"
        # Push the secrets file via colmena keys, then activate
        export COLMENA_TARGET_HOST="$ip"
        export COLMENA_SSH_KEY="$tmp/ssh.key"
        # Sync the server secrets file directly via scp (atomic, mode 600)
        scp -i "$tmp/ssh.key" \
            -o StrictHostKeyChecking=accept-new \
            -o UserKnownHostsFile="$tf_dir/known_hosts" \
            "$tmp/server-secrets.yaml" \
            "root@$ip:${serverSecretsPath}.new"
        ssh -i "$tmp/ssh.key" \
            -o StrictHostKeyChecking=accept-new \
            -o UserKnownHostsFile="$tf_dir/known_hosts" \
            "root@$ip" \
            "install -m 600 ${serverSecretsPath}.new ${serverSecretsPath} && rm ${serverSecretsPath}.new"
        cd "$root"
        colmena apply --on ${name} switch --impure
      else
        echo "==> Fresh host — bootstrapping with nixos-anywhere"
        extra="$(mktemp -d)"
        chmod 700 "$extra"
        # Server age priv → for sops-nix activation
        install -D -m 600 <(printf '%s' "$age_priv") "$extra/var/lib/sops-nix/key.txt"
        # Server-bound secrets blob
        install -D -m 600 "$tmp/server-secrets.yaml" "$extra${serverSecretsPath}"
        nix run ${nixos-anywhere} -- \
          --flake "$root#${name}" \
          --extra-files "$extra" \
          -i "$tmp/ssh.key" \
          "root@$ip"
        rm -rf "$extra"
      fi
    '';
  };

  mkDestroyApp = { stateDir, tfConfig, sopsFile, envFromSops }:
    pkgs.writeShellApplication {
      excludeShellChecks = [ "SC2155" "SC2046" "SC2086" ];
      name = "infra-destroy";
      runtimeInputs = [ pkgs.opentofu pkgs.git pkgs.coreutils pkgs.sops pkgs.yq-go ];
      text = ''
        ${preamble { inherit stateDir tfConfig sopsFile; }}
        ${envFromSopsScript envFromSops}
        ( cd "$tf_dir" && tofu destroy -auto-approve )
      '';
    };

  mkImportApp = { stateDir, tfConfig, sopsFile, envFromSops, importMap }:
    pkgs.writeShellApplication {
      excludeShellChecks = [ "SC2155" "SC2046" "SC2086" ];
      name = "infra-import";
      runtimeInputs = [ pkgs.opentofu pkgs.git pkgs.coreutils pkgs.sops pkgs.yq-go ];
      text = ''
        ${preamble { inherit stateDir tfConfig sopsFile; }}
        ${envFromSopsScript envFromSops}
        cd "$tf_dir"
        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (resource: id:
          "tofu import '${resource}' '${id}' || true"
        ) importMap)}
      '';
    };

  mkSopsApp = { sopsFile }:
    pkgs.writeShellApplication {
      excludeShellChecks = [ "SC2155" "SC2046" "SC2086" ];
      name = "sops-edit";
      runtimeInputs = [ pkgs.sops ];
      text = ''
        # No .sops.yaml; recipients live in the file's metadata header.
        exec sops --config /dev/null "$@" "${toString sopsFile}"
      '';
    };

  mkUmbrellaApp = { hostNames, hostApps }:
    pkgs.writeShellApplication {
      excludeShellChecks = [ "SC2155" "SC2046" "SC2086" ];
      name = "infra";
      runtimeInputs = [];
      text = lib.concatMapStringsSep "\n"
        (n: "${hostApps.${n}}/bin/infra-${n}")
        hostNames;
    };

in {

  # Returns an attrset suitable for `apps.${system}` (consumer just merges in).
  mkApps = {
    terranixModules,
    sopsFile,                                # path to operator sops file
    hosts,                                   # see below
    stateDir         ? ".tf-state",
    envFromSops   ? {},                   # { ENV_VAR_NAME = sopsKey; } → raw env vars
    importMap        ? {},
  }:
    let
      tfConfig = terranix.lib.terranixConfiguration {
        inherit system;
        modules = terranixModules;
      };

      # Fixed defaults for per-host outputs (consumer overrides only if needed)
      defaults = name: {
        ipOutput        = "${name}_ip";
        sshPrivOutput   = "${name}_ssh_priv";
        sshPubOutput    = "${name}_ssh_pub";
        agePrivOutput   = "${name}_age_priv";
        agePubOutput    = "${name}_age_pub";
        serverSecrets   = [];
        serverSecretsFromTfState = {};
        serverSecretsPath = "/var/lib/sops-nix/buildfarm-secrets.yaml";
      };

      hostApps = lib.mapAttrs (name: cfg:
        mkHostApp ((defaults name) // cfg // {
          inherit name stateDir tfConfig sopsFile envFromSops;
        })
      ) hosts;

      hostAppOutputs = lib.mapAttrs (n: drv: {
        type = "app";
        program = "${drv}/bin/infra-${n}";
      }) hostApps;

      destroyApp  = mkDestroyApp  { inherit stateDir tfConfig sopsFile envFromSops; };
      importApp   = mkImportApp   { inherit stateDir tfConfig sopsFile envFromSops importMap; };
      sopsApp     = mkSopsApp     { inherit sopsFile; };
      umbrellaApp = mkUmbrellaApp { hostNames = lib.attrNames hosts; inherit hostApps; };

      maybeImport = lib.optionalAttrs (importMap != {}) {
        import = { type = "app"; program = "${importApp}/bin/infra-import"; };
      };
    in {
      infra = {
        type = "app";
        program = "${umbrellaApp}/bin/infra";
        destroy = { type = "app"; program = "${destroyApp}/bin/infra-destroy"; };
      } // hostAppOutputs // maybeImport;
      sops-edit = { type = "app"; program = "${sopsApp}/bin/sops-edit"; };
    };

  # Use this for `deployment` in your colmenaHive node defs.
  mkDeployment = {
    targetHost = let h = builtins.getEnv "COLMENA_TARGET_HOST"; in
      if h == "" then null else h;
    targetUser = "root";
    sshOptions =
      let k = builtins.getEnv "COLMENA_SSH_KEY"; in
      lib.optionals (k != "") [ "-i" k ];
  };
}
